### ISSUE TITLE
希望加入多开功能

### ISSUE THREAD

**Issue by xcgx** [iranee/qnap-nps#1]
希望可以添加对接多个服务端的功能。
或者app本身可以多开

**Comment by asseywang** [comment]
+1 需要多开

**Comment by asseywang** [comment]
@xcgx 老哥,你怎么解决多开的问题的? 再起一个Docker么?

**Comment by iranee** [comment]
更新了下，试试

**Comment by asseywang** [comment]
> 更新了下，试试

大佬~ , 怎么操作才能多开?

**Comment by iranee** [comment]
> > 更新了下，试试
> 
> 
> 
> 大佬~ , 怎么操作才能多开?

先看看配置文件是否支持，如果不支持只能自制插件，改启动名字和路径。或者开多个docker版
