### ISSUE TITLE
大佬 官方版本不更新了,这里有一个分支版本可以持续迭代更新:https://github.com/yisier/nps/releases

### ISSUE THREAD

**Issue by asseywang** [iranee/qnap-nps#2]
https://github.com/yisier/nps/releases

**Comment by iranee** [comment]
> https://github.com/yisier/nps/releases

好的，更新了一波

**Comment by asseywang** [comment]
好的，感谢大佬了
Alireza ***@***.***>于2023年1月14日 周六17:29写道：
