### ISSUE TITLE
已经配置但是无法连接

### ISSUE THREAD

**Issue by nwq115212** [iranee/qnap-nps#4]
<img width="582" alt="image" src="https://github.com/iranee/qnap-nps/assets/88225943/2845b7bf-3ede-4bc8-94ab-edcde6fa6c98">
<img width="1202" alt="image" src="https://github.com/iranee/qnap-nps/assets/88225943/4dc8a6de-5814-45a7-9063-81f5a195eb41">
服务器端确定配置没问题我拿其他客户端试过了，但是qnap上面的客户端就是连接不成功
用配置文件配置的方法也试过了还是没有用
<img width="733" alt="image" src="https://github.com/iranee/qnap-nps/assets/88225943/52c419f9-a5a7-4464-b94d-dccc574ba2d1">
最后面的提示是：进程运行中，PID：19847 | 程序版本： 0.26.16
但是实际服务器端显示离线

**Comment by nwq115212** [comment]
我的qnap是212p3，系统版本5.0.1.2425，使用的arm64

**Comment by curryhendry** [comment]
我也是这样，本地提示运行中，NPS那边还是离线。

**Comment by nwq115212** [comment]
> 我也是这样，本地提示运行中，NPS那边还是离线。

我已经放弃了

**Comment by iranee** [comment]
有很多内网穿透的产品，这个配置比较繁琐也没有跟进更新，你尝试使用https://github.com/yisier/nps  这里的服务端来连接，如果还不可用，放弃吧，还用其他产品。或者有更好的产品推荐给我。安好
